### PR TITLE
Redo bugfix

### LINKED ISSUE #178: Redo should not be possible unless the previous command is undo
add task1. undo. mark task2. redo. Currently the last redo will add task1. However this is not the behaviour of redo in any other programs. Redo only reverts changes made by undo and will be cleared if the previous command is not undo.

add task1, it fails. redo. Currently redo will try to add task1 again. This is also not how redo works in other programs.

### PR DESCRIPTION
**Pull request by shaunthium**
Closes #178

### CODE REVIEW

File: src/main/java/cs2103/v15_1j/jimjim/command/AddCommand.java [hunk 1]
```diff
@@ -46,7 +46,8 @@ public UIFeedback undo(ControllerStates conStates) {
     @Override
     public UIFeedback execute(ControllerStates conStates) {
         conStates.masterList.add(taskEvent);
-        
+        conStates.resetRedoHistory();
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/AddCommand.java]: This way of doing it is a bit laborious / not nice to me, as you have to add this to every single command. How about checking in `JJController` whether the command is UndoCommand, if not clear the redo stack?
