### PR TITLE
Fix bug with SaveLocationCommand not updating storage's save file path.

### LINKED ISSUE #225: Fix bug with ChangeSaveLocation command not updating storage's save file path

### PR DESCRIPTION
**Pull request by shaunthium**
Closes #225

### CODE REVIEW

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 1]
```diff
@@ -23,11 +23,13 @@ public UIFeedback execute(ControllerStates conStates) {
     	conStates.config.savePath = savePath;
     	
     	if (conStates.storage.saveConfig(conStates.config)) {
+    		conStates.storage.setSaveFile(savePath);
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: need to save the data to the new location also. Hence you should move this to before the if else, and add to the if condition to check that saving the current data to the new location succeeds. Please add a test case for trying to save to an invalid path and see whether the program handles it correctly as well.

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 2]
```diff
@@ -20,10 +22,22 @@ public String getSavePath() {
...
     	String backup = conStates.config.savePath;
+    	
+    	try {
+    		File f = new File(backup);	
+    	} catch (Exception e) {
+    		return new FailureFeedback("Invalid file path specified!");
+    	}
+    	
+    	String extension = savePath.substring(savePath.length()-5, savePath.length()); 
+    	if (!extension.equals(".json")) {
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: No need to check for the right extension. I don't see anything wrong if user wants to save it as a `txt` file. Also to check for extension you should use java's method instead of manually checking like this.

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 3]
```diff
@@ -20,10 +22,22 @@ public String getSavePath() {
...
+    		return new FailureFeedback("Wrong file extension specified!");
+    	}
+    	
     	conStates.config.savePath = savePath;
+    	conStates.storage.setSaveFile(savePath);
     	
     	if (conStates.storage.saveConfig(conStates.config)) {
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: Need to save to the new location too.

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 4]
```diff
@@ -20,10 +22,22 @@ public String getSavePath() {
     @Override
     public UIFeedback execute(ControllerStates conStates) {
     	String backup = conStates.config.savePath;
+    	
+    	try {
+    		File f = new File(backup);
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: why checking the old file path?

File: src/test/java/cs2103/v15_1j/jimjim/command/SaveLocationCommandTest.java [hunk 5]
```diff
@@ -61,4 +61,13 @@ public void testStorageError() {
 		assertEquals(backup, conStates.config.savePath);
 	}
 
+	@Test
+	public void testInvalidFilePath() {
+		String backup = conStates.config.savePath;
+		String invalidSavePath = "test/save/path/save_data.txt"; // Wrong file extension
```
Comment (tran-tien-dat) [inline src/test/java/cs2103/v15_1j/jimjim/command/SaveLocationCommandTest.java]: For invalid file path i mean something like `+0 \/ &*#`

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 6]
```diff
@@ -23,20 +23,28 @@ public String getSavePath() {
     @Override
     public UIFeedback execute(ControllerStates conStates) {
     	String backup = conStates.config.savePath;
+    	File file = null;
     	
-    	try {
-    		File f = new File(backup);	
-    	} catch (Exception e) {
+    	if (savePath.contains(" ")) {
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: Why is this invalid? We can have space in file / folder name what?

Comment (shaunthium) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: It creates two folders. The space is allowed only if you use a backslash.

On Tuesday, 5 April 2016, Tran Tien Dat <notifications@github.com> wrote:

> In src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java
> <https://github.com/cs2103jan2016-v15-1j/main/pull/226#discussion_r58491235>
> :
>
> >      	
> > -    	try {
> > -    		File f = new File(backup);	
> > -    	} catch (Exception e) {
> > +    	if (savePath.contains(" ")) {
>
> Why is this invalid? We can have space in file / folder name what?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cs2103jan2016-v15-1j/main/pull/226/files/89a6d808151dae517bec90547ee9f6a0c28f8498..de18f8254985571e283763a90a40b4951983eb02#r58491235>
>


-- 

Shaun Thium (Mr.)
*National University of Singapore*
B.Comp (Computer Science) | University Scholar's Programme

File: src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java [hunk 7]
```diff
@@ -21,7 +23,28 @@ public String getSavePath() {
     @Override
     public UIFeedback execute(ControllerStates conStates) {
     	String backup = conStates.config.savePath;
+    	File file = null;
+    	
+    	if (savePath.contains(" ")) {
```
Comment (tran-tien-dat) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: then "abc\ def" should be allowed right but you are not allowing it if you have this condition

Comment (shaunthium) [inline src/main/java/cs2103/v15_1j/jimjim/command/SaveLocationCommand.java]: then if the user types in with a space we should add the `\` for them? if not it'll create two directories
